codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "dist/**/*"
  - "coverage/**/*"
  - "**/*.test.ts"
  - "**/__tests__/**"
  - "src/cli.ts"
  - "src/index.ts"
  - "jest.config.json"