name: Manual Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        - prerelease
      dry_run:
        description: 'Dry run (test without publishing)'
        required: false
        type: boolean
        default: false

jobs:
  manual-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests and validation
      run: |
        npm run type-check
        npm run lint
        npm run test:ci
        npm run build
        
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Version bump
      run: |
        OLD_VERSION=$(npm pkg get version | tr -d '"')
        echo "Current version: $OLD_VERSION"
        
        if [ "${{ inputs.version_bump }}" = "prerelease" ]; then
          npm version prerelease --preid=beta
        else
          npm version ${{ inputs.version_bump }}
        fi
        
        NEW_VERSION=$(npm pkg get version | tr -d '"')
        echo "New version: $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        
    - name: Build with new version
      run: npm run build
      
    - name: Test package locally
      run: |
        npm pack
        PACKAGE_FILE=$(ls *.tgz)
        echo "Testing local installation of $PACKAGE_FILE"
        npm install -g "$PACKAGE_FILE"
        context-mcp --help
        
    - name: Dry run publish
      if: inputs.dry_run
      run: |
        echo "🧪 Dry run mode - testing publish without actually publishing"
        npm publish --dry-run
        echo "✅ Dry run completed successfully"
        
    - name: Publish to npm
      if: '!inputs.dry_run'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Push version changes
      if: '!inputs.dry_run'
      run: |
        git push origin main
        git push origin v${{ env.NEW_VERSION }}
        
    - name: Create GitHub Release
      if: '!inputs.dry_run'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        release_name: Release v${{ env.NEW_VERSION }}
        body: |
          Release v${{ env.NEW_VERSION }}
          
          Changes in this release:
          - Manual release triggered via workflow dispatch
          - Version bump: ${{ inputs.version_bump }}
          
        draft: false
        prerelease: ${{ contains(env.NEW_VERSION, 'beta') }}
        
    - name: Verify npm publication
      if: '!inputs.dry_run'
      run: |
        echo "Waiting for npm registry propagation..."
        sleep 30
        PACKAGE_NAME=$(npm pkg get name | tr -d '"')
        npm view "$PACKAGE_NAME@${{ env.NEW_VERSION }}" version
        echo "✅ Package successfully published to npm"
